services:
  python-store:
    image: ${COAKKA_SAMPLE_PYTHON_STORE_IMAGE:-docker.io/gabrielgun1983/sample-python-store:0.2.0-94a5729-remote}
    hostname: python-store
    environment:
      COAKKA_SAMPLE_STORE_WEB_HOST: 0.0.0.0
      COAKKA_SAMPLE_STORE_WEB_PORT: "8081"
      COAKKA_SAMPLE_STORE_RUNTIME_BIND_HOST: auto
      COAKKA_SAMPLE_STORE_RUNTIME_HOST: python-store
      COAKKA_SAMPLE_STORE_RUNTIME_PORT: "19232"
      COAKKA_SAMPLE_NODE_RUNTIME_HOST: node-web
      COAKKA_SAMPLE_NODE_RUNTIME_PORT: "19231"
    ports:
      - "8081:8081"
    networks:
      - coakka-node-python

  node-web:
    image: ${COAKKA_SAMPLE_NODE_WEB_IMAGE:-docker.io/gabrielgun1983/sample-node-web:0.2.0-94a5729-remote}
    hostname: node-web
    depends_on:
      - python-store
    environment:
      COAKKA_SAMPLE_WEB_HOST: 0.0.0.0
      COAKKA_SAMPLE_WEB_PORT: "8080"
      COAKKA_SAMPLE_NODE_RUNTIME_BIND_HOST: auto
      COAKKA_SAMPLE_NODE_RUNTIME_HOST: node-web
      COAKKA_SAMPLE_NODE_RUNTIME_PORT: "19231"
      COAKKA_SAMPLE_STORE_RUNTIME_HOST: python-store
      COAKKA_SAMPLE_STORE_RUNTIME_PORT: "19232"
    ports:
      - "8080:8080"
    networks:
      - coakka-node-python

networks:
  coakka-node-python:
