server:
  port: 8081

spring:
  application:
    name: customer-web

sample:
  connector:
    system-name: customer-web
    node-id: customer-web-node
    local-target: samples.customer.frontend
    local-host: 127.0.0.1
    local-port: 19101
    peer-target: samples.customer.store
    peer-host: 127.0.0.1
    peer-port: 19102
    generation: 1
