quarkus.http.port=8083
quarkus.application.name=customer-quarkus-local
quarkus.banner.enabled=false
coakka.runtime.enabled=true
coakka.runtime.mode=local
coakka.runtime.system-name=customer-quarkus-local
coakka.runtime.node-id=customer-quarkus-local-node
coakka.runtime.source-target=samples.customer.frontend
coakka.runtime.queue-capacity=128
coakka.runtime.strict-no-drop=true
coakka.runtime.separate-delivered-request-lane=true
coakka.runtime.local-endpoint-host=127.0.0.1
coakka.runtime.local-endpoint-port=19182
