kotlin.code.style=official
coakkaV2JvmVersion=2.5.3
coakkaV2NativeCoreVersion=2.5.1
coakkaV2NativeGitCommit=26f7944de4a4e0598845a54e4775f9463a9e33be
coakkaRuntimeJvmSourceRepository=https://github.com/phuong-tran/coakka-samples
coakkaRuntimeJvmSourceTag=runtime-jvm-2.5.3
coakkaRuntimeJvmSourcePath=source-mirrors/runtime-jvm/2.5.3
