cmake_minimum_required(VERSION 3.24)
project(coakka_http_runtime_c_sample LANGUAGES C)

find_package(CoAkkaHttpHost 1.0.0 EXACT CONFIG REQUIRED)
find_package(Threads REQUIRED)

add_executable(coakka-http-c main.c)
target_link_libraries(coakka-http-c PRIVATE CoAkkaHttp::host Threads::Threads)
target_compile_features(coakka-http-c PRIVATE c_std_11)
add_executable(coakka-http-c-security security.c)
target_link_libraries(coakka-http-c-security PRIVATE CoAkkaHttp::host Threads::Threads)
target_compile_features(coakka-http-c-security PRIVATE c_std_11)
if(MSVC)
  target_compile_options(coakka-http-c PRIVATE /W4 /WX)
  target_compile_options(coakka-http-c-security PRIVATE /W4 /WX)
else()
  target_compile_options(coakka-http-c PRIVATE -Wall -Wextra -Wpedantic -Werror)
  target_compile_options(coakka-http-c-security PRIVATE -Wall -Wextra -Wpedantic -Werror)
endif()
