# Fail closed on edited, omitted, duplicate or unlisted test-suite source.
# This verifies an evidence inventory, not artifact authenticity/signatures.
cmake_policy(SET CMP0057 NEW)
if(NOT DEFINED TEST_SOURCE_DIR)
  set(TEST_SOURCE_DIR "${CMAKE_CURRENT_LIST_DIR}")
endif()
file(STRINGS "${TEST_SOURCE_DIR}/SOURCE-MANIFEST.sha256" entries)
set(listed)
foreach(entry IN LISTS entries)
  if(NOT entry MATCHES "^([0-9a-f]+)  ([A-Za-z0-9_.-]+)$")
    message(FATAL_ERROR "Malformed test-source manifest entry")
  endif()
  set(expected "${CMAKE_MATCH_1}")
  set(name "${CMAKE_MATCH_2}")
  string(LENGTH "${expected}" digest_length)
  if(NOT digest_length EQUAL 64 OR name IN_LIST listed)
    message(FATAL_ERROR "Invalid or duplicate test-source digest: ${name}")
  endif()
  if(NOT EXISTS "${TEST_SOURCE_DIR}/${name}" OR IS_DIRECTORY "${TEST_SOURCE_DIR}/${name}")
    message(FATAL_ERROR "Missing test-source file: ${name}")
  endif()
  file(SHA256 "${TEST_SOURCE_DIR}/${name}" actual)
  if(NOT actual STREQUAL expected)
    message(FATAL_ERROR "Test-source drift: ${name}")
  endif()
  list(APPEND listed "${name}")
endforeach()
file(GLOB inventory RELATIVE "${TEST_SOURCE_DIR}"
  "${TEST_SOURCE_DIR}/*.c" "${TEST_SOURCE_DIR}/*.cc"
  "${TEST_SOURCE_DIR}/*.h" "${TEST_SOURCE_DIR}/*.cmake"
  "${TEST_SOURCE_DIR}/*.sh" "${TEST_SOURCE_DIR}/*.md")
list(APPEND inventory CMakeLists.txt)
list(SORT inventory)
list(SORT listed)
if(NOT inventory STREQUAL listed)
  message(FATAL_ERROR "Test-source manifest inventory mismatch")
endif()
message(STATUS "Installed test-source manifest verified")
