cmake_minimum_required(VERSION 3.24)
project(coakka_http_runtime_cpp_sample LANGUAGES CXX)

find_package(CoAkkaHttpHost 1.0.0 EXACT CONFIG REQUIRED)
find_package(Threads REQUIRED)

add_executable(coakka-http-cpp main.cpp)
target_link_libraries(coakka-http-cpp PRIVATE CoAkkaHttp::host Threads::Threads)
target_compile_features(coakka-http-cpp PRIVATE cxx_std_20)
add_executable(coakka-http-cpp-security security.cpp)
target_link_libraries(coakka-http-cpp-security PRIVATE CoAkkaHttp::host Threads::Threads)
target_compile_features(coakka-http-cpp-security PRIVATE cxx_std_20)
if(MSVC)
  target_compile_options(coakka-http-cpp PRIVATE /W4 /WX /permissive-)
  target_compile_options(coakka-http-cpp-security PRIVATE /W4 /WX /permissive-)
else()
  target_compile_options(coakka-http-cpp PRIVATE -Wall -Wextra -Wpedantic -Werror)
  target_compile_options(coakka-http-cpp-security PRIVATE -Wall -Wextra -Wpedantic -Werror)
endif()
